// auth/user
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// todos
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const TOGGLE_TODO_COMPLETION = 'TOGGLE_TODO_COMPLETION';
export const SET_TODOS_DISPLAY_CRITERIA = 'SET_TODOS_DISPLAY_CRITERIA';

// ui
export const SET_MODAL_MESSAGE = 'SET_LOADING_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
